import { describe, it, expect } from "vitest";
import { renderWikiSite, bannerFor, type RenderInput } from "../src/wiki/renderer.js";

const baseCtx = {
  owner: "acme",
  repo: "widgets",
  commit: "abcdef1234567890",
  timestamp: "2026-07-20T00:00:00.000Z",
  repoUrl: "https://github.com/acme/widgets",
  config: {},
};

function input(): RenderInput {
  return {
    context: baseCtx,
    modules: [
      {
        path: "design",
        description: "Design docs",
        indexMarkdown: "# Design\n\nOverview.",
        concepts: [
          { sourceRelPath: "patterns/retry.md", title: "Retry", rawMarkdown: "# Retry\n\nBody." },
        ],
        assets: [],
      },
    ],
  };
}

describe("renderWikiSite skeleton", () => {
  it("emits landing and concept pages with banner", () => {
    const site = renderWikiSite(input());
    const paths = site.pages.map((p) => p.path);
    expect(paths).toContain("design/index.md");
    expect(paths).toContain("design/patterns/retry.md");
    const concept = site.pages.find((p) => p.path === "design/patterns/retry.md")!;
    expect(concept.content.startsWith(bannerFor("widgets", "design", "Retry"))).toBe(true);
    expect(concept.content).toContain("# Retry");
  });

  it("landing page includes the module description and index markdown", () => {
    const site = renderWikiSite(input());
    const landing = site.pages.find((p) => p.path === "design/index.md")!;
    expect(landing.content).toContain("Overview.");
  });

  it("sorts pages by path", () => {
    const site = renderWikiSite(input());
    const paths = site.pages.map((p) => p.path);
    const sorted = [...paths].sort();
    expect(paths).toEqual(sorted);
  });

  it("bannerFor matches the required format", () => {
    expect(bannerFor("widgets", "design", "Retry")).toBe(
      "> 📘 widgets › design › Retry · _Generated by Open Knowledge Hub — do not edit._",
    );
  });

  it("de-dups case-insensitive path collisions with a warning", () => {
    const inp = input();
    inp.modules[0].concepts = [
      { sourceRelPath: "a.md", title: "A", rawMarkdown: "x" },
      { sourceRelPath: "A.md", title: "A2", rawMarkdown: "y" },
    ];
    const site = renderWikiSite(inp);
    const paths = site.pages.map((p) => p.path).filter((p) => p.startsWith("design/") && p !== "design/index.md");
    expect(paths).toContain("design/a.md");
    expect(paths.some((p) => /-2\.md$/.test(p))).toBe(true);
    expect(site.warnings.some((w) => w.kind === "collision")).toBe(true);
  });
});
