import { posix } from "node:path";
import { OKF_RESERVED } from "../modules/loaders/okf.js";
import { parseFrontmatter } from "../util/frontmatter.js";
import { pathSlug } from "./slug.js";
import type { WikiConfig } from "./config.js";

export type RenderConcept = { sourceRelPath: string; title: string; rawMarkdown: string };
export type RenderAsset = { sourceRelPath: string; bytes: Buffer };
export type RenderModule = {
  path: string;
  description?: string;
  indexMarkdown?: string;
  concepts: RenderConcept[];
  assets: RenderAsset[];
};
export type RenderContextInfo = {
  owner: string;
  repo: string;
  commit: string;
  timestamp: string;
  repoUrl: string;
  config: WikiConfig;
};
export type RenderInput = { module: RenderModule; context: RenderContextInfo };
export type WikiPage = { path: string; content: string };
export type WikiAsset = { path: string; bytes: Buffer };
export type RenderWarning = { kind: "collision" | "dangling-link" | "dangling-asset"; message: string };
export type WikiSite = { pages: WikiPage[]; assets: WikiAsset[]; warnings: RenderWarning[] };

const HOME_SLUG = "Home";
const INDEX_KEY = "index.md";

/** Slim concept banner (no module segment — the whole wiki is one module). */
export function bannerFor(repo: string, title: string): string {
  return `> 📘 ${repo} › ${title} · _Generated by Open Knowledge Hub — do not edit._`;
}

type PageRec = { slug: string; title: string; path: string };
type RewriteContext = {
  currentDir: string; // POSIX dir of the current page's module-relative source (or "." at module root)
  pageIndex: Map<string, string>; // module-rel path (lowercased) -> slug ("Home" for index.md)
  assets: RenderAsset[];
};

/** Drop a leading YAML frontmatter block so published wiki pages stay clean. */
const stripFrontmatter = (markdown: string): string => parseFrontmatter(markdown).body;

const titleCase = (s: string): string => (s ? s[0].toUpperCase() + s.slice(1) : s);

function splitAnchor(target: string): [string, string | undefined] {
  const i = target.indexOf("#");
  if (i === -1) return [target, undefined];
  return [target.slice(0, i), target.slice(i + 1)];
}

/** Resolve a link target to a module-relative path. Leading slash = module root. */
function resolveTarget(pathPart: string, currentDir: string): string {
  return pathPart.startsWith("/")
    ? posix.normalize(pathPart.slice(1))
    : posix.normalize(posix.join(currentDir, pathPart));
}

/** Non-reserved concepts, sorted by module-relative path for deterministic output. */
function orderedConcepts(module: RenderModule): RenderConcept[] {
  return [...module.concepts]
    .filter((c) => !OKF_RESERVED.has(c.sourceRelPath))
    .sort((a, b) => a.sourceRelPath.localeCompare(b.sourceRelPath));
}

/** Assign a unique flat slug per concept and build the module-relative -> slug index. */
function buildPages(
  module: RenderModule,
): { records: PageRec[]; pageIndex: Map<string, string>; warnings: RenderWarning[] } {
  const warnings: RenderWarning[] = [];
  const pageIndex = new Map<string, string>();
  pageIndex.set(INDEX_KEY, HOME_SLUG);
  const used = new Set<string>();
  const records: PageRec[] = [];

  for (const c of orderedConcepts(module)) {
    const desired = pathSlug(c.sourceRelPath);
    let slug = desired;
    let n = 1;
    while (used.has(slug.toLowerCase())) {
      n += 1;
      slug = `${desired}-${n}`;
      warnings.push({ kind: "collision", message: `Slug collision for ${desired}; using ${slug}` });
    }
    used.add(slug.toLowerCase());
    pageIndex.set(c.sourceRelPath.toLowerCase(), slug);
    records.push({ slug, title: c.title, path: c.sourceRelPath });
  }
  return { records, pageIndex, warnings };
}

/** Rewrite internal markdown links/assets to flat wiki slugs / filenames. */
function rewriteBody(
  rawBody: string,
  ctx: RewriteContext,
): { body: string; assets: WikiAsset[]; warnings: RenderWarning[] } {
  const warnings: RenderWarning[] = [];
  const collectedAssets: WikiAsset[] = [];
  const linkRe = /(\]\()([^)]+)(\))/g;

  const body = rawBody.replace(linkRe, (whole, open, rawTarget, close) => {
    const target = rawTarget.trim();
    if (/^[a-z]+:/i.test(target) || target.startsWith("#")) return whole;
    const [pathPart, anchor] = splitAnchor(target);
    if (pathPart === "") return whole;
    const resolved = resolveTarget(pathPart, ctx.currentDir);
    const suffix = anchor ? `#${anchor}` : "";

    if (!pathPart.toLowerCase().endsWith(".md")) {
      // asset reference
      const asset = ctx.assets.find((a) => a.sourceRelPath === resolved);
      if (!asset) {
        warnings.push({ kind: "dangling-asset", message: `Missing asset ${target}` });
        return whole;
      }
      const flat = pathSlug(asset.sourceRelPath);
      collectedAssets.push({ path: flat, bytes: asset.bytes });
      return `${open}${flat}${suffix}${close}`;
    }

    const slug = ctx.pageIndex.get(resolved.toLowerCase());
    if (!slug) {
      warnings.push({ kind: "dangling-link", message: `Dangling link ${target}` });
      return whole;
    }
    return `${open}${slug}${suffix}${close}`;
  });

  return { body, assets: collectedAssets, warnings };
}

function groupBySubfolder(recs: PageRec[]): { root: PageRec[]; groups: { name: string; items: PageRec[] }[] } {
  const root: PageRec[] = [];
  const byFolder = new Map<string, PageRec[]>();
  for (const r of recs) {
    const i = r.path.indexOf("/");
    if (i === -1) {
      root.push(r);
    } else {
      const folder = r.path.slice(0, i);
      const bucket = byFolder.get(folder) ?? [];
      bucket.push(r);
      byFolder.set(folder, bucket);
    }
  }
  const groups = [...byFolder.entries()]
    .map(([name, items]) => ({ name, items: [...items].sort((a, b) => a.title.localeCompare(b.title)) }))
    .sort((a, b) => a.name.localeCompare(b.name));
  root.sort((a, b) => a.title.localeCompare(b.title));
  return { root, groups };
}

function renderSidebar(records: PageRec[]): WikiPage {
  const { root, groups } = groupBySubfolder(records);
  const lines: string[] = ["[🏠 Home](Home)", ""];
  for (const r of root) lines.push(`- [${r.title}](${r.slug})`);
  if (root.length > 0) lines.push("");
  for (const g of groups) {
    lines.push(`<details open><summary><b>${titleCase(g.name)}</b> (${g.items.length})</summary>`, "");
    for (const r of g.items) lines.push(`- [${r.title}](${r.slug})`);
    lines.push("", "</details>", "");
  }
  return { path: "_Sidebar.md", content: lines.join("\n").trimEnd() + "\n" };
}

function renderHome(
  module: RenderModule,
  ctx: RenderContextInfo,
  records: PageRec[],
  pageIndex: Map<string, string>,
): { page: WikiPage; assets: WikiAsset[]; warnings: RenderWarning[] } {
  if (module.indexMarkdown) {
    const rewritten = rewriteBody(stripFrontmatter(module.indexMarkdown), {
      currentDir: ".",
      pageIndex,
      assets: module.assets,
    });
    return {
      page: { path: "Home.md", content: rewritten.body.trimEnd() + "\n" },
      assets: rewritten.assets,
      warnings: rewritten.warnings,
    };
  }
  const title = ctx.config.title ?? ctx.repo;
  const lines: string[] = [`# ${title}`, ""];
  if (module.description) lines.push(module.description, "");
  const { root, groups } = groupBySubfolder(records);
  for (const r of root) lines.push(`- [${r.title}](${r.slug})`);
  if (root.length > 0) lines.push("");
  for (const g of groups) {
    lines.push(`### ${titleCase(g.name)}`, "");
    for (const r of g.items) lines.push(`- [${r.title}](${r.slug})`);
    lines.push("");
  }
  return { page: { path: "Home.md", content: lines.join("\n").trimEnd() + "\n" }, assets: [], warnings: [] };
}

function renderFooter(ctx: RenderContextInfo): WikiPage {
  const shortCommit = ctx.commit.slice(0, 7);
  const lines: string[] = [
    `_Generated by [Open Knowledge Hub](https://github.com/dryotta/open-knowledge-hub) from [${ctx.owner}/${ctx.repo}](${ctx.repoUrl}) @ \`${shortCommit}\` on ${ctx.timestamp}._`,
  ];
  if (ctx.config.footer) lines.push("", ctx.config.footer);
  return { path: "_Footer.md", content: lines.join("\n") + "\n" };
}

function dedupeAssets(assets: WikiAsset[]): WikiAsset[] {
  const seen = new Set<string>();
  const out: WikiAsset[] = [];
  for (const a of assets) {
    if (seen.has(a.path)) continue;
    seen.add(a.path);
    out.push(a);
  }
  return out;
}

export function renderWikiSite(input: RenderInput): WikiSite {
  const { module, context } = input;
  const { records, pageIndex, warnings } = buildPages(module);
  const pages: WikiPage[] = [];
  let assets: WikiAsset[] = [];
  const allWarnings: RenderWarning[] = [...warnings];

  const conceptByPath = new Map(module.concepts.map((c) => [c.sourceRelPath, c] as const));
  for (const rec of records) {
    const concept = conceptByPath.get(rec.path)!;
    const rewritten = rewriteBody(stripFrontmatter(concept.rawMarkdown), {
      currentDir: posix.dirname(rec.path),
      pageIndex,
      assets: module.assets,
    });
    allWarnings.push(...rewritten.warnings);
    assets.push(...rewritten.assets);
    const content = `${bannerFor(context.repo, rec.title)}\n\n${rewritten.body}`;
    pages.push({ path: `${rec.slug}.md`, content });
  }

  const home = renderHome(module, context, records, pageIndex);
  allWarnings.push(...home.warnings);
  assets.push(...home.assets);
  pages.push(home.page);
  pages.push(renderSidebar(records));
  pages.push(renderFooter(context));

  assets = dedupeAssets(assets);
  pages.sort((a, b) => a.path.localeCompare(b.path));
  assets.sort((a, b) => a.path.localeCompare(b.path));
  return { pages, assets, warnings: allWarnings };
}
