import { OKF_RESERVED } from "../modules/loaders/okf.js";
import type { WikiConfig } from "./config.js";

export type RenderConcept = { sourceRelPath: string; title: string; rawMarkdown: string };
export type RenderAsset = { sourceRelPath: string; bytes: Buffer };
export type RenderModule = {
  path: string;
  description?: string;
  indexMarkdown?: string;
  concepts: RenderConcept[];
  assets: RenderAsset[];
};
export type RenderContextInfo = {
  owner: string;
  repo: string;
  commit: string;
  timestamp: string;
  repoUrl: string;
  config: WikiConfig;
};
export type RenderInput = { modules: RenderModule[]; context: RenderContextInfo };
export type WikiPage = { path: string; content: string };
export type WikiAsset = { path: string; bytes: Buffer };
export type RenderWarning = { kind: "collision" | "dangling-link" | "dangling-asset"; message: string };
export type WikiSite = { pages: WikiPage[]; assets: WikiAsset[]; warnings: RenderWarning[] };
export type RewriteResult = { body: string; assets: WikiAsset[]; warnings: RenderWarning[] };
export type RewriteContext = {
  moduleName: string;
  currentWikiPath: string;
  pageIndex: Map<string, string>;
  assetIndex: Map<string, string>;
  moduleAssets: RenderAsset[];
};

export function bannerFor(repo: string, moduleName: string, title: string): string {
  return `> 📘 ${repo} › ${moduleName} › ${title} · _Generated by Open Knowledge Hub — do not edit._`;
}

type RawPage = { path: string; banner?: string; body: string };

function sortedModules(input: RenderInput): RenderModule[] {
  return [...input.modules].sort((a, b) => a.path.localeCompare(b.path));
}

function buildPageIndex(modules: RenderModule[]): Map<string, string> {
  const index = new Map<string, string>();
  for (const m of modules) {
    index.set(`${m.path}/index.md`.toLowerCase(), `${m.path}/index.md`);
    for (const c of m.concepts) {
      if (OKF_RESERVED.has(c.sourceRelPath)) continue;
      const key = `${m.path}/${c.sourceRelPath}`.toLowerCase();
      index.set(key, `${m.path}/${c.sourceRelPath}`);
    }
  }
  return index;
}

function buildAssetIndex(modules: RenderModule[]): Map<string, string> {
  const index = new Map<string, string>();
  for (const m of modules) {
    for (const a of m.assets) {
      const key = `${m.path}/${a.sourceRelPath}`.toLowerCase();
      index.set(key, `${m.path}/${a.sourceRelPath}`);
    }
  }
  return index;
}

function renderModulePages(
  m: RenderModule,
  ctx: RenderContextInfo,
  used: Set<string>,
): { pages: RawPage[]; warnings: RenderWarning[] } {
  const warnings: RenderWarning[] = [];
  const pages: RawPage[] = [];

  const claim = (desired: string): string => {
    let candidate = desired;
    let n = 1;
    while (used.has(candidate.toLowerCase())) {
      n += 1;
      candidate = desired.replace(/\.md$/, `-${n}.md`);
      warnings.push({ kind: "collision", message: `Path collision for ${desired}; using ${candidate}` });
    }
    used.add(candidate.toLowerCase());
    return candidate;
  };

  // landing
  const landingPath = claim(`${m.path}/index.md`);
  const landingParts: string[] = [`# ${m.path}`];
  if (m.description) landingParts.push("", m.description);
  if (m.indexMarkdown) landingParts.push("", m.indexMarkdown);
  pages.push({
    path: landingPath,
    banner: bannerFor(ctx.repo, m.path, m.path),
    body: landingParts.join("\n"),
  });

  const concepts = [...m.concepts]
    .filter((c) => !OKF_RESERVED.has(c.sourceRelPath))
    .sort((a, b) => a.sourceRelPath.localeCompare(b.sourceRelPath));
  for (const c of concepts) {
    const path = claim(`${m.path}/${c.sourceRelPath}`);
    pages.push({ path, banner: bannerFor(ctx.repo, m.path, c.title), body: c.rawMarkdown });
  }
  return { pages, warnings };
}

// Stub — replaced in Task 5 (links) and Task 6 (assets).
function rewriteBody(rawBody: string, _ctx: RewriteContext): RewriteResult {
  return { body: rawBody, assets: [], warnings: [] };
}

// Stub — implemented in Task 4.
function renderStructuralPages(_input: RenderInput, _pages: WikiPage[]): WikiPage[] {
  return [];
}

function dedupeAssets(assets: WikiAsset[]): WikiAsset[] {
  const seen = new Set<string>();
  const out: WikiAsset[] = [];
  for (const a of assets) {
    if (seen.has(a.path)) continue;
    seen.add(a.path);
    out.push(a);
  }
  return out;
}

export function renderWikiSite(input: RenderInput): WikiSite {
  const modules = sortedModules(input);
  const pageIndex = buildPageIndex(modules);
  const assetIndex = buildAssetIndex(modules);
  const warnings: RenderWarning[] = [];
  const pages: WikiPage[] = [];
  let assets: WikiAsset[] = [];
  const used = new Set<string>();

  for (const m of modules) {
    const rendered = renderModulePages(m, input.context, used);
    warnings.push(...rendered.warnings);
    for (const raw of rendered.pages) {
      const ctx: RewriteContext = {
        moduleName: m.path,
        currentWikiPath: raw.path,
        pageIndex,
        assetIndex,
        moduleAssets: m.assets,
      };
      const rewritten = rewriteBody(raw.body, ctx);
      warnings.push(...rewritten.warnings);
      assets.push(...rewritten.assets);
      const content = raw.banner ? `${raw.banner}\n\n${rewritten.body}` : rewritten.body;
      pages.push({ path: raw.path, content });
    }
  }

  pages.push(...renderStructuralPages(input, pages));
  assets = dedupeAssets(assets);

  pages.sort((a, b) => a.path.localeCompare(b.path));
  assets.sort((a, b) => a.path.localeCompare(b.path));
  return { pages, assets, warnings };
}
