import { posix } from "node:path";
import { OKF_RESERVED } from "../modules/loaders/okf.js";
import { parseFrontmatter } from "../util/frontmatter.js";
import type { WikiConfig } from "./config.js";

export type RenderConcept = { sourceRelPath: string; title: string; rawMarkdown: string };
export type RenderAsset = { sourceRelPath: string; bytes: Buffer };
export type RenderModule = {
  path: string;
  description?: string;
  indexMarkdown?: string;
  concepts: RenderConcept[];
  assets: RenderAsset[];
};
export type RenderContextInfo = {
  owner: string;
  repo: string;
  commit: string;
  timestamp: string;
  repoUrl: string;
  config: WikiConfig;
};
export type RenderInput = { modules: RenderModule[]; context: RenderContextInfo };
export type WikiPage = { path: string; content: string };
export type WikiAsset = { path: string; bytes: Buffer };
export type RenderWarning = { kind: "collision" | "dangling-link" | "dangling-asset"; message: string };
export type WikiSite = { pages: WikiPage[]; assets: WikiAsset[]; warnings: RenderWarning[] };
export type RewriteResult = { body: string; assets: WikiAsset[]; warnings: RenderWarning[] };
export type RewriteContext = {
  moduleName: string;
  currentWikiPath: string;
  pageIndex: Map<string, string>;
  assetIndex: Map<string, string>;
  moduleAssets: RenderAsset[];
};

export function bannerFor(repo: string, moduleName: string, title: string): string {
  return `> 📘 ${repo} › ${moduleName} › ${title} · _Generated by Open Knowledge Hub — do not edit._`;
}

type RawPage = { path: string; banner?: string; body: string };
type NavEntry = { module: string; landingPath: string; concepts: { title: string; path: string }[] };

const stripMd = (p: string): string => p.replace(/\.md$/, "");

/** Drop a leading YAML frontmatter block so published wiki pages stay clean. */
const stripFrontmatter = (markdown: string): string => parseFrontmatter(markdown).body;

function sortedModules(input: RenderInput): RenderModule[] {
  return [...input.modules].sort((a, b) => a.path.localeCompare(b.path));
}

function buildPageIndex(modules: RenderModule[]): Map<string, string> {
  const index = new Map<string, string>();
  for (const m of modules) {
    index.set(`${m.path}/index.md`.toLowerCase(), `${m.path}/index.md`);
    for (const c of m.concepts) {
      if (OKF_RESERVED.has(c.sourceRelPath)) continue;
      const key = `${m.path}/${c.sourceRelPath}`.toLowerCase();
      index.set(key, `${m.path}/${c.sourceRelPath}`);
    }
  }
  return index;
}

function buildAssetIndex(modules: RenderModule[]): Map<string, string> {
  const index = new Map<string, string>();
  for (const m of modules) {
    for (const a of m.assets) {
      const key = `${m.path}/${a.sourceRelPath}`.toLowerCase();
      index.set(key, `${m.path}/${a.sourceRelPath}`);
    }
  }
  return index;
}

function renderModulePages(
  m: RenderModule,
  ctx: RenderContextInfo,
  used: Set<string>,
): { pages: RawPage[]; warnings: RenderWarning[]; nav: NavEntry } {
  const warnings: RenderWarning[] = [];
  const pages: RawPage[] = [];

  const claim = (desired: string): string => {
    let candidate = desired;
    let n = 1;
    while (used.has(candidate.toLowerCase())) {
      n += 1;
      candidate = desired.replace(/\.md$/, `-${n}.md`);
      warnings.push({ kind: "collision", message: `Path collision for ${desired}; using ${candidate}` });
    }
    used.add(candidate.toLowerCase());
    return candidate;
  };

  // landing
  const landingPath = claim(`${m.path}/index.md`);
  const nav: NavEntry = { module: m.path, landingPath, concepts: [] };
  const landingParts: string[] = [`# ${m.path}`];
  if (m.description) landingParts.push("", m.description);
  if (m.indexMarkdown) landingParts.push("", stripFrontmatter(m.indexMarkdown));
  pages.push({
    path: landingPath,
    banner: bannerFor(ctx.repo, m.path, m.path),
    body: landingParts.join("\n"),
  });

  const concepts = [...m.concepts]
    .filter((c) => !OKF_RESERVED.has(c.sourceRelPath))
    .sort((a, b) => a.sourceRelPath.localeCompare(b.sourceRelPath));
  for (const c of concepts) {
    const path = claim(`${m.path}/${c.sourceRelPath}`);
    pages.push({ path, banner: bannerFor(ctx.repo, m.path, c.title), body: stripFrontmatter(c.rawMarkdown) });
    nav.concepts.push({ title: c.title, path });
  }
  return { pages, warnings, nav };
}

function rewriteBody(rawBody: string, ctx: RewriteContext): RewriteResult {
  const warnings: RenderWarning[] = [];
  const collectedAssets: WikiAsset[] = [];
  const currentDir = posix.dirname(ctx.currentWikiPath); // e.g. "design/patterns"
  const linkRe = /(\]\()([^)]+)(\))/g;

  const body = rawBody.replace(linkRe, (whole, open, rawTarget, close) => {
    const target = rawTarget.trim();
    if (/^[a-z]+:/i.test(target) || target.startsWith("#")) return whole;
    const [pathPart, anchor] = splitAnchor(target);
    if (pathPart === "") return whole;
    // A leading slash is module-root-relative; otherwise resolve against the current page dir.
    const resolved = pathPart.startsWith("/")
      ? posix.normalize(posix.join(ctx.moduleName, pathPart.slice(1)))
      : posix.normalize(posix.join(currentDir, pathPart));
    if (!pathPart.toLowerCase().endsWith(".md")) {
      // asset reference
      const moduleRel = resolved.startsWith(`${ctx.moduleName}/`)
        ? resolved.slice(ctx.moduleName.length + 1)
        : resolved;
      const asset = ctx.moduleAssets.find((a) => a.sourceRelPath === moduleRel);
      if (!asset) {
        warnings.push({ kind: "dangling-asset", message: `Missing asset ${target} in ${ctx.currentWikiPath}` });
        return whole;
      }
      const wikiAssetPath = `${ctx.moduleName}/${asset.sourceRelPath}`;
      collectedAssets.push({ path: wikiAssetPath, bytes: asset.bytes });
      const rel = relativePosix(currentDir, wikiAssetPath);
      return `${open}${rel}${anchor ? `#${anchor}` : ""}${close}`;
    }
    // resolve relative to current page's source dir (same as wiki dir)
    const key = resolved.toLowerCase();
    const wikiTarget = ctx.pageIndex.get(key);
    if (!wikiTarget) {
      warnings.push({ kind: "dangling-link", message: `Dangling link ${target} in ${ctx.currentWikiPath}` });
      return whole;
    }
    const rel = relativePosix(currentDir, wikiTarget.replace(/\.md$/, ""));
    return `${open}${rel}${anchor ? `#${anchor}` : ""}${close}`;
  });

  return { body, assets: collectedAssets, warnings };
}

function splitAnchor(target: string): [string, string | undefined] {
  const i = target.indexOf("#");
  if (i === -1) return [target, undefined];
  return [target.slice(0, i), target.slice(i + 1)];
}

function relativePosix(fromDir: string, toPath: string): string {
  const rel = posix.relative(fromDir, toPath);
  return rel === "" ? "." : rel;
}

function renderStructuralPages(input: RenderInput, nav: NavEntry[]): WikiPage[] {
  const { context } = input;
  const title = context.config.title ?? context.repo;

  const homeLines: string[] = [`# ${title}`, ""];
  if (nav.length === 0) {
    homeLines.push("_No knowledge modules are published yet._");
  } else {
    homeLines.push("## Modules", "");
    for (const entry of nav) {
      const mod = input.modules.find((m) => m.path === entry.module);
      const desc = mod?.description ? ` — ${mod.description}` : "";
      homeLines.push(`- [${entry.module}](${stripMd(entry.landingPath)})${desc}`);
    }
  }
  const home: WikiPage = { path: "Home.md", content: homeLines.join("\n") + "\n" };

  const sideLines: string[] = [];
  for (const entry of nav) {
    sideLines.push(`## ${entry.module}`, "", `- [Overview](${stripMd(entry.landingPath)})`);
    for (const c of entry.concepts) {
      sideLines.push(`- [${c.title}](${stripMd(c.path)})`);
    }
    sideLines.push("");
  }
  const sidebar: WikiPage = { path: "_Sidebar.md", content: sideLines.join("\n").trimEnd() + "\n" };

  const shortCommit = context.commit.slice(0, 7);
  const footerLines: string[] = [
    `_Generated by [Open Knowledge Hub](https://github.com/dryotta/open-knowledge-hub) from [${context.owner}/${context.repo}](${context.repoUrl}) @ \`${shortCommit}\` on ${context.timestamp}._`,
  ];
  if (context.config.footer) footerLines.push("", context.config.footer);
  const footer: WikiPage = { path: "_Footer.md", content: footerLines.join("\n") + "\n" };

  return [home, sidebar, footer];
}

function dedupeAssets(assets: WikiAsset[]): WikiAsset[] {
  const seen = new Set<string>();
  const out: WikiAsset[] = [];
  for (const a of assets) {
    if (seen.has(a.path)) continue;
    seen.add(a.path);
    out.push(a);
  }
  return out;
}

export function renderWikiSite(input: RenderInput): WikiSite {
  const modules = sortedModules(input);
  const pageIndex = buildPageIndex(modules);
  const assetIndex = buildAssetIndex(modules);
  const warnings: RenderWarning[] = [];
  const pages: WikiPage[] = [];
  let assets: WikiAsset[] = [];
  const used = new Set<string>();
  const nav: NavEntry[] = [];

  for (const m of modules) {
    const rendered = renderModulePages(m, input.context, used);
    warnings.push(...rendered.warnings);
    nav.push(rendered.nav);
    for (const raw of rendered.pages) {
      const ctx: RewriteContext = {
        moduleName: m.path,
        currentWikiPath: raw.path,
        pageIndex,
        assetIndex,
        moduleAssets: m.assets,
      };
      const rewritten = rewriteBody(raw.body, ctx);
      warnings.push(...rewritten.warnings);
      assets.push(...rewritten.assets);
      const content = raw.banner ? `${raw.banner}\n\n${rewritten.body}` : rewritten.body;
      pages.push({ path: raw.path, content });
    }
  }

  pages.push(...renderStructuralPages(input, nav));
  assets = dedupeAssets(assets);

  pages.sort((a, b) => a.path.localeCompare(b.path));
  assets.sort((a, b) => a.path.localeCompare(b.path));
  return { pages, assets, warnings };
}
